import { Home, GraduationCap, Users, Backpack, Building, Heart, Plane, Briefcase, HeartHandshake } from "lucide-react"

export const CATEGORIES = [
    { name: "Student", icon: GraduationCap, slug: "student" },
    { name: "Family", icon: Users, slug: "family" },
    { name: "Traveller", icon: Plane, slug: "traveller" },
    { name: "Backpacker", icon: Backpack, slug: "backpacker" },
    { name: "Long-term", icon: Building, slug: "long-term" },
    { name: "Short-term", icon: Home, slug: "short-term" },
    { name: "Sharing", icon: Heart, slug: "sharing" },
    { name: "Professionals", icon: Briefcase, slug: "professionals" },
    { name: "Couple Friendly", icon: HeartHandshake, slug: "couple-friendly" },
]

export const COUNTRIES = [
    { name: "Afghanistan", code: "AF", flag: "https://flagcdn.com/w40/af.png", phoneCode: "+93", currency: "AFN" },
    { name: "Albania", code: "AL", flag: "https://flagcdn.com/w40/al.png", phoneCode: "+355", currency: "ALL" },
    { name: "Algeria", code: "DZ", flag: "https://flagcdn.com/w40/dz.png", phoneCode: "+213", currency: "DZD" },
    { name: "Andorra", code: "AD", flag: "https://flagcdn.com/w40/ad.png", phoneCode: "+376", currency: "EUR" },
    { name: "Angola", code: "AO", flag: "https://flagcdn.com/w40/ao.png", phoneCode: "+244", currency: "AOA" },
    { name: "Argentina", code: "AR", flag: "https://flagcdn.com/w40/ar.png", phoneCode: "+54", currency: "ARS" },
    { name: "Armenia", code: "AM", flag: "https://flagcdn.com/w40/am.png", phoneCode: "+374", currency: "AMD" },
    { name: "Australia", code: "AU", flag: "https://flagcdn.com/w40/au.png", phoneCode: "+61", currency: "AUD" },
    { name: "Austria", code: "AT", flag: "https://flagcdn.com/w40/at.png", phoneCode: "+43", currency: "EUR" },
    { name: "Azerbaijan", code: "AZ", flag: "https://flagcdn.com/w40/az.png", phoneCode: "+994", currency: "AZN" },
    { name: "Bahrain", code: "BH", flag: "https://flagcdn.com/w40/bh.png", phoneCode: "+973", currency: "BHD" },
    { name: "Bangladesh", code: "BD", flag: "https://flagcdn.com/w40/bd.png", phoneCode: "+880", currency: "BDT" },
    { name: "Belarus", code: "BY", flag: "https://flagcdn.com/w40/by.png", phoneCode: "+375", currency: "BYN" },
    { name: "Belgium", code: "BE", flag: "https://flagcdn.com/w40/be.png", phoneCode: "+32", currency: "EUR" },
    { name: "Belize", code: "BZ", flag: "https://flagcdn.com/w40/bz.png", phoneCode: "+501", currency: "BZD" },
    { name: "Benin", code: "BJ", flag: "https://flagcdn.com/w40/bj.png", phoneCode: "+229", currency: "XOF" },
    { name: "Bhutan", code: "BT", flag: "https://flagcdn.com/w40/bt.png", phoneCode: "+975", currency: "BTN" },
    { name: "Bolivia", code: "BO", flag: "https://flagcdn.com/w40/bo.png", phoneCode: "+591", currency: "BOB" },
    { name: "Bosnia and Herzegovina", code: "BA", flag: "https://flagcdn.com/w40/ba.png", phoneCode: "+387", currency: "BAM" },
    { name: "Botswana", code: "BW", flag: "https://flagcdn.com/w40/bw.png", phoneCode: "+267", currency: "BWP" },
    { name: "Brazil", code: "BR", flag: "https://flagcdn.com/w40/br.png", phoneCode: "+55", currency: "BRL" },
    { name: "Brunei", code: "BN", flag: "https://flagcdn.com/w40/bn.png", phoneCode: "+673", currency: "BND" },
    { name: "Bulgaria", code: "BG", flag: "https://flagcdn.com/w40/bg.png", phoneCode: "+359", currency: "BGN" },
    { name: "Burkina Faso", code: "BF", flag: "https://flagcdn.com/w40/bf.png", phoneCode: "+226", currency: "XOF" },
    { name: "Burundi", code: "BI", flag: "https://flagcdn.com/w40/bi.png", phoneCode: "+257", currency: "BIF" },
    { name: "Cambodia", code: "KH", flag: "https://flagcdn.com/w40/kh.png", phoneCode: "+855", currency: "KHR" },
    { name: "Cameroon", code: "CM", flag: "https://flagcdn.com/w40/cm.png", phoneCode: "+237", currency: "XAF" },
    { name: "Canada", code: "CA", flag: "https://flagcdn.com/w40/ca.png", phoneCode: "+1", currency: "CAD" },
    { name: "Cape Verde", code: "CV", flag: "https://flagcdn.com/w40/cv.png", phoneCode: "+238", currency: "CVE" },
    { name: "Central African Republic", code: "CF", flag: "https://flagcdn.com/w40/cf.png", phoneCode: "+236", currency: "XAF" },
    { name: "Chad", code: "TD", flag: "https://flagcdn.com/w40/td.png", phoneCode: "+235", currency: "XAF" },
    { name: "Chile", code: "CL", flag: "https://flagcdn.com/w40/cl.png", phoneCode: "+56", currency: "CLP" },
    { name: "China", code: "CN", flag: "https://flagcdn.com/w40/cn.png", phoneCode: "+86", currency: "CNY" },
    { name: "Colombia", code: "CO", flag: "https://flagcdn.com/w40/co.png", phoneCode: "+57", currency: "COP" },
    { name: "Comoros", code: "KM", flag: "https://flagcdn.com/w40/km.png", phoneCode: "+269", currency: "KMF" },
    { name: "Costa Rica", code: "CR", flag: "https://flagcdn.com/w40/cr.png", phoneCode: "+506", currency: "CRC" },
    { name: "Croatia", code: "HR", flag: "https://flagcdn.com/w40/hr.png", phoneCode: "+385", currency: "EUR" },
    { name: "Cuba", code: "CU", flag: "https://flagcdn.com/w40/cu.png", phoneCode: "+53", currency: "CUP" },
    { name: "Cyprus", code: "CY", flag: "https://flagcdn.com/w40/cy.png", phoneCode: "+357", currency: "EUR" },
    { name: "Czech Republic", code: "CZ", flag: "https://flagcdn.com/w40/cz.png", phoneCode: "+420", currency: "CZK" },
    { name: "Denmark", code: "DK", flag: "https://flagcdn.com/w40/dk.png", phoneCode: "+45", currency: "DKK" },
    { name: "Djibouti", code: "DJ", flag: "https://flagcdn.com/w40/dj.png", phoneCode: "+253", currency: "DJF" },
    { name: "Ecuador", code: "EC", flag: "https://flagcdn.com/w40/ec.png", phoneCode: "+593", currency: "USD" },
    { name: "Egypt", code: "EG", flag: "https://flagcdn.com/w40/eg.png", phoneCode: "+20", currency: "EGP" },
    { name: "El Salvador", code: "SV", flag: "https://flagcdn.com/w40/sv.png", phoneCode: "+503", currency: "USD" },
    { name: "Equatorial Guinea", code: "GQ", flag: "https://flagcdn.com/w40/gq.png", phoneCode: "+240", currency: "XAF" },
    { name: "Eritrea", code: "ER", flag: "https://flagcdn.com/w40/er.png", phoneCode: "+291", currency: "ERN" },
    { name: "Estonia", code: "EE", flag: "https://flagcdn.com/w40/ee.png", phoneCode: "+372", currency: "EUR" },
    { name: "Ethiopia", code: "ET", flag: "https://flagcdn.com/w40/et.png", phoneCode: "+251", currency: "ETB" },
    { name: "Fiji", code: "FJ", flag: "https://flagcdn.com/w40/fj.png", phoneCode: "+679", currency: "FJD" },
    { name: "Finland", code: "FI", flag: "https://flagcdn.com/w40/fi.png", phoneCode: "+358", currency: "EUR" },
    { name: "France", code: "FR", flag: "https://flagcdn.com/w40/fr.png", phoneCode: "+33", currency: "EUR" },
    { name: "Gabon", code: "GA", flag: "https://flagcdn.com/w40/ga.png", phoneCode: "+241", currency: "XAF" },
    { name: "Gambia", code: "GM", flag: "https://flagcdn.com/w40/gm.png", phoneCode: "+220", currency: "GMD" },
    { name: "Georgia", code: "GE", flag: "https://flagcdn.com/w40/ge.png", phoneCode: "+995", currency: "GEL" },
    { name: "Germany", code: "DE", flag: "https://flagcdn.com/w40/de.png", phoneCode: "+49", currency: "EUR" },
    { name: "Ghana", code: "GH", flag: "https://flagcdn.com/w40/gh.png", phoneCode: "+233", currency: "GHS" },
    { name: "Greece", code: "GR", flag: "https://flagcdn.com/w40/gr.png", phoneCode: "+30", currency: "EUR" },
    { name: "Guatemala", code: "GT", flag: "https://flagcdn.com/w40/gt.png", phoneCode: "+502", currency: "GTQ" },
    { name: "Guinea", code: "GN", flag: "https://flagcdn.com/w40/gn.png", phoneCode: "+224", currency: "GNF" },
    { name: "Guyana", code: "GY", flag: "https://flagcdn.com/w40/gy.png", phoneCode: "+592", currency: "GYD" },
    { name: "Haiti", code: "HT", flag: "https://flagcdn.com/w40/ht.png", phoneCode: "+509", currency: "HTG" },
    { name: "Honduras", code: "HN", flag: "https://flagcdn.com/w40/hn.png", phoneCode: "+504", currency: "HNL" },
    { name: "Hong Kong", code: "HK", flag: "https://flagcdn.com/w40/hk.png", phoneCode: "+852", currency: "HKD" },
    { name: "Hungary", code: "HU", flag: "https://flagcdn.com/w40/hu.png", phoneCode: "+36", currency: "HUF" },
    { name: "Iceland", code: "IS", flag: "https://flagcdn.com/w40/is.png", phoneCode: "+354", currency: "ISK" },
    { name: "India", code: "IN", flag: "https://flagcdn.com/w40/in.png", phoneCode: "+91", currency: "INR" },
    { name: "Indonesia", code: "ID", flag: "https://flagcdn.com/w40/id.png", phoneCode: "+62", currency: "IDR" },
    { name: "Iran", code: "IR", flag: "https://flagcdn.com/w40/ir.png", phoneCode: "+98", currency: "IRR" },
    { name: "Iraq", code: "IQ", flag: "https://flagcdn.com/w40/iq.png", phoneCode: "+964", currency: "IQD" },
    { name: "Ireland", code: "IE", flag: "https://flagcdn.com/w40/ie.png", phoneCode: "+353", currency: "EUR" },
    { name: "Israel", code: "IL", flag: "https://flagcdn.com/w40/il.png", phoneCode: "+972", currency: "ILS" },
    { name: "Italy", code: "IT", flag: "https://flagcdn.com/w40/it.png", phoneCode: "+39", currency: "EUR" },
    { name: "Jamaica", code: "JM", flag: "https://flagcdn.com/w40/jm.png", phoneCode: "+1-876", currency: "JMD" },
    { name: "Japan", code: "JP", flag: "https://flagcdn.com/w40/jp.png", phoneCode: "+81", currency: "JPY" },
    { name: "Jordan", code: "JO", flag: "https://flagcdn.com/w40/jo.png", phoneCode: "+962", currency: "JOD" },
    { name: "Kazakhstan", code: "KZ", flag: "https://flagcdn.com/w40/kz.png", phoneCode: "+7", currency: "KZT" },
    { name: "Kenya", code: "KE", flag: "https://flagcdn.com/w40/ke.png", phoneCode: "+254", currency: "KES" },
    { name: "Kuwait", code: "KW", flag: "https://flagcdn.com/w40/kw.png", phoneCode: "+965", currency: "KWD" },
    { name: "Kyrgyzstan", code: "KG", flag: "https://flagcdn.com/w40/kg.png", phoneCode: "+996", currency: "KGS" },
    { name: "Laos", code: "LA", flag: "https://flagcdn.com/w40/la.png", phoneCode: "+856", currency: "LAK" },
    { name: "Latvia", code: "LV", flag: "https://flagcdn.com/w40/lv.png", phoneCode: "+371", currency: "EUR" },
    { name: "Lebanon", code: "LB", flag: "https://flagcdn.com/w40/lb.png", phoneCode: "+961", currency: "LBP" },
    { name: "Lesotho", code: "LS", flag: "https://flagcdn.com/w40/ls.png", phoneCode: "+266", currency: "LSL" },
    { name: "Liberia", code: "LR", flag: "https://flagcdn.com/w40/lr.png", phoneCode: "+231", currency: "LRD" },
    { name: "Libya", code: "LY", flag: "https://flagcdn.com/w40/ly.png", phoneCode: "+218", currency: "LYD" },
    { name: "Liechtenstein", code: "LI", flag: "https://flagcdn.com/w40/li.png", phoneCode: "+423", currency: "CHF" },
    { name: "Lithuania", code: "LT", flag: "https://flagcdn.com/w40/lt.png", phoneCode: "+370", currency: "EUR" },
    { name: "Luxembourg", code: "LU", flag: "https://flagcdn.com/w40/lu.png", phoneCode: "+352", currency: "EUR" },
    { name: "Macau", code: "MO", flag: "https://flagcdn.com/w40/mo.png", phoneCode: "+853", currency: "MOP" },
    { name: "Macedonia", code: "MK", flag: "https://flagcdn.com/w40/mk.png", phoneCode: "+389", currency: "MKD" },
    { name: "Madagascar", code: "MG", flag: "https://flagcdn.com/w40/mg.png", phoneCode: "+261", currency: "MGA" },
    { name: "Malawi", code: "MW", flag: "https://flagcdn.com/w40/mw.png", phoneCode: "+265", currency: "MWK" },
    { name: "Malaysia", code: "MY", flag: "https://flagcdn.com/w40/my.png", phoneCode: "+60", currency: "MYR" },
    { name: "Maldives", code: "MV", flag: "https://flagcdn.com/w40/mv.png", phoneCode: "+960", currency: "MVR" },
    { name: "Mali", code: "ML", flag: "https://flagcdn.com/w40/ml.png", phoneCode: "+223", currency: "XOF" },
    { name: "Malta", code: "MT", flag: "https://flagcdn.com/w40/mt.png", phoneCode: "+356", currency: "EUR" },
    { name: "Mexico", code: "MX", flag: "https://flagcdn.com/w40/mx.png", phoneCode: "+52", currency: "MXN" },
    { name: "Moldova", code: "MD", flag: "https://flagcdn.com/w40/md.png", phoneCode: "+373", currency: "MDL" },
    { name: "Monaco", code: "MC", flag: "https://flagcdn.com/w40/mc.png", phoneCode: "+377", currency: "EUR" },
    { name: "Mongolia", code: "MN", flag: "https://flagcdn.com/w40/mn.png", phoneCode: "+976", currency: "MNT" },
    { name: "Montenegro", code: "ME", flag: "https://flagcdn.com/w40/me.png", phoneCode: "+382", currency: "EUR" },
    { name: "Morocco", code: "MA", flag: "https://flagcdn.com/w40/ma.png", phoneCode: "+212", currency: "MAD" },
    { name: "Mozambique", code: "MZ", flag: "https://flagcdn.com/w40/mz.png", phoneCode: "+258", currency: "MZN" },
    { name: "Myanmar", code: "MM", flag: "https://flagcdn.com/w40/mm.png", phoneCode: "+95", currency: "MMK" },
    { name: "Namibia", code: "NA", flag: "https://flagcdn.com/w40/na.png", phoneCode: "+264", currency: "NAD" },
    { name: "Nepal", code: "NP", flag: "https://flagcdn.com/w40/np.png", phoneCode: "+977", currency: "NPR" },
    { name: "Netherlands", code: "NL", flag: "https://flagcdn.com/w40/nl.png", phoneCode: "+31", currency: "EUR" },
    { name: "New Zealand", code: "NZ", flag: "https://flagcdn.com/w40/nz.png", phoneCode: "+64", currency: "NZD" },
    { name: "Nicaragua", code: "NI", flag: "https://flagcdn.com/w40/ni.png", phoneCode: "+505", currency: "NIO" },
    { name: "Niger", code: "NE", flag: "https://flagcdn.com/w40/ne.png", phoneCode: "+227", currency: "XOF" },
    { name: "Nigeria", code: "NG", flag: "https://flagcdn.com/w40/ng.png", phoneCode: "+234", currency: "NGN" },
    { name: "North Korea", code: "KP", flag: "https://flagcdn.com/w40/kp.png", phoneCode: "+850", currency: "KPW" },
    { name: "Norway", code: "NO", flag: "https://flagcdn.com/w40/no.png", phoneCode: "+47", currency: "NOK" },
    { name: "Oman", code: "OM", flag: "https://flagcdn.com/w40/om.png", phoneCode: "+968", currency: "OMR" },
    { name: "Pakistan", code: "PK", flag: "https://flagcdn.com/w40/pk.png", phoneCode: "+92", currency: "PKR" },
    { name: "Palestine", code: "PS", flag: "https://flagcdn.com/w40/ps.png", phoneCode: "+970", currency: "ILS" },
    { name: "Panama", code: "PA", flag: "https://flagcdn.com/w40/pa.png", phoneCode: "+507", currency: "PAB" },
    { name: "Papua New Guinea", code: "PG", flag: "https://flagcdn.com/w40/pg.png", phoneCode: "+675", currency: "PGK" },
    { name: "Paraguay", code: "PY", flag: "https://flagcdn.com/w40/py.png", phoneCode: "+595", currency: "PYG" },
    { name: "Peru", code: "PE", flag: "https://flagcdn.com/w40/pe.png", phoneCode: "+51", currency: "PEN" },
    { name: "Philippines", code: "PH", flag: "https://flagcdn.com/w40/ph.png", phoneCode: "+63", currency: "PHP" },
    { name: "Poland", code: "PL", flag: "https://flagcdn.com/w40/pl.png", phoneCode: "+48", currency: "PLN" },
    { name: "Portugal", code: "PT", flag: "https://flagcdn.com/w40/pt.png", phoneCode: "+351", currency: "EUR" },
    { name: "Qatar", code: "QA", flag: "https://flagcdn.com/w40/qa.png", phoneCode: "+974", currency: "QAR" },
    { name: "Romania", code: "RO", flag: "https://flagcdn.com/w40/ro.png", phoneCode: "+40", currency: "RON" },
    { name: "Russia", code: "RU", flag: "https://flagcdn.com/w40/ru.png", phoneCode: "+7", currency: "RUB" },
    { name: "Rwanda", code: "RW", flag: "https://flagcdn.com/w40/rw.png", phoneCode: "+250", currency: "RWF" },
    { name: "Saudi Arabia", code: "SA", flag: "https://flagcdn.com/w40/sa.png", phoneCode: "+966", currency: "SAR" },
    { name: "Senegal", code: "SN", flag: "https://flagcdn.com/w40/sn.png", phoneCode: "+221", currency: "XOF" },
    { name: "Serbia", code: "RS", flag: "https://flagcdn.com/w40/rs.png", phoneCode: "+381", currency: "RSD" },
    { name: "Singapore", code: "SG", flag: "https://flagcdn.com/w40/sg.png", phoneCode: "+65", currency: "SGD" },
    { name: "Slovakia", code: "SK", flag: "https://flagcdn.com/w40/sk.png", phoneCode: "+421", currency: "EUR" },
    { name: "Slovenia", code: "SI", flag: "https://flagcdn.com/w40/si.png", phoneCode: "+386", currency: "EUR" },
    { name: "Somalia", code: "SO", flag: "https://flagcdn.com/w40/so.png", phoneCode: "+252", currency: "SOS" },
    { name: "South Africa", code: "ZA", flag: "https://flagcdn.com/w40/za.png", phoneCode: "+27", currency: "ZAR" },
    { name: "South Korea", code: "KR", flag: "https://flagcdn.com/w40/kr.png", phoneCode: "+82", currency: "KRW" },
    { name: "Spain", code: "ES", flag: "https://flagcdn.com/w40/es.png", phoneCode: "+34", currency: "EUR" },
    { name: "Sri Lanka", code: "LK", flag: "https://flagcdn.com/w40/lk.png", phoneCode: "+94", currency: "LKR" },
    { name: "Sudan", code: "SD", flag: "https://flagcdn.com/w40/sd.png", phoneCode: "+249", currency: "SDG" },
    { name: "Sweden", code: "SE", flag: "https://flagcdn.com/w40/se.png", phoneCode: "+46", currency: "SEK" },
    { name: "Switzerland", code: "CH", flag: "https://flagcdn.com/w40/ch.png", phoneCode: "+41", currency: "CHF" },
    { name: "Syria", code: "SY", flag: "https://flagcdn.com/w40/sy.png", phoneCode: "+963", currency: "SYP" },
    { name: "Taiwan", code: "TW", flag: "https://flagcdn.com/w40/tw.png", phoneCode: "+886", currency: "TWD" },
    { name: "Tajikistan", code: "TJ", flag: "https://flagcdn.com/w40/tj.png", phoneCode: "+992", currency: "TJS" },
    { name: "Tanzania", code: "TZ", flag: "https://flagcdn.com/w40/tz.png", phoneCode: "+255", currency: "TZS" },
    { name: "Thailand", code: "TH", flag: "https://flagcdn.com/w40/th.png", phoneCode: "+66", currency: "THB" },
    { name: "Tunisia", code: "TN", flag: "https://flagcdn.com/w40/tn.png", phoneCode: "+216", currency: "TND" },
    { name: "Turkey", code: "TR", flag: "https://flagcdn.com/w40/tr.png", phoneCode: "+90", currency: "TRY" },
    { name: "Turkmenistan", code: "TM", flag: "https://flagcdn.com/w40/tm.png", phoneCode: "+993", currency: "TMT" },
    { name: "Uganda", code: "UG", flag: "https://flagcdn.com/w40/ug.png", phoneCode: "+256", currency: "UGX" },
    { name: "Ukraine", code: "UA", flag: "https://flagcdn.com/w40/ua.png", phoneCode: "+380", currency: "UAH" },
    { name: "United Arab Emirates", code: "AE", flag: "https://flagcdn.com/w40/ae.png", phoneCode: "+971", currency: "AED" },
    { name: "United Kingdom", code: "UK", flag: "https://flagcdn.com/w40/gb.png", phoneCode: "+44", currency: "GBP" },
    { name: "United States of America", code: "US", flag: "https://flagcdn.com/w40/us.png", phoneCode: "+1", currency: "USD" },
    { name: "Uruguay", code: "UY", flag: "https://flagcdn.com/w40/uy.png", phoneCode: "+598", currency: "UYU" },
    { name: "Uzbekistan", code: "UZ", flag: "https://flagcdn.com/w40/uz.png", phoneCode: "+998", currency: "UZS" },
    { name: "Venezuela", code: "VE", flag: "https://flagcdn.com/w40/ve.png", phoneCode: "+58", currency: "VES" },
    { name: "Vietnam", code: "VN", flag: "https://flagcdn.com/w40/vn.png", phoneCode: "+84", currency: "VND" },
    { name: "Yemen", code: "YE", flag: "https://flagcdn.com/w40/ye.png", phoneCode: "+967", currency: "YER" },
    { name: "Zambia", code: "ZM", flag: "https://flagcdn.com/w40/zm.png", phoneCode: "+260", currency: "ZMW" },
    { name: "Zimbabwe", code: "ZW", flag: "https://flagcdn.com/w40/zw.png", phoneCode: "+263", currency: "ZWL" },
]
